### ISSUE TITLE
Export CALCULATE_RESPONSIVE_STATE

### ISSUE THREAD

**Issue by TheFuzzball** [aaivazis/redux-responsive#15]
There are cases where reduxResponsive needs to be augmented with additional data,
it would be ideal if the CALCULATE_RESPONSIVE_STATE constant can be exported in this module.

**Comment by aaivazis** [comment]
Seems reasonable to me. Do you have a particular use case in mind? Maybe it's something we should add to the reducer

**Comment by TheFuzzball** [comment]
Sorry I've taken so long to respond, and thanks for the quick update!

I'm finding that as my app grows I want to nest some content together, which I can do by composing reducers (which is particularly easy because they're pure functions).

I am re-using the browser namespace for other browser-related things like this:

```js
export default function browser(state = {}, action) {
	if ( action.type === CALCULATE_RESPONSIVE_STATE ) {
		return {
			...responsiveStateReducer(state, action),
			clientWidth: document.documentElement.clientWidth,
		}
	} else {
		return state
	}
}
```
