### ISSUE TITLE
Empty media type

### ISSUE THREAD

**Issue by tstavinoha** [aaivazis/redux-responsive#3]
Hello, nifty little lib you got here!

I have a problem with mediaType property. At first couple of actions it is set to 'infinity', but soon becomes an empty object. 
I've tracked the problem down to createResponsiveStateReducer.getMediaType and the call to transform, it does some weird reassigns instead of mutating the result.

It is easy to quickfix:

    return transform(mediaQueries, (result, query, type) => {
        // if the browser matches the media query
        if (matchMedia(query).matches) {
            // use the current media type
            /* eslint-disable no-param-reassign */
            result.type = type
            /* eslint-enable no-param-reassign */
        }
    }).type

The real question is, why use media queries in the first place? Other properties are calculated based  solely on breakpoints, it is very simple and intuitive. This whole media matching stuff just seems like an unnecessary complexity

**Comment by aaivazis** [comment]
Thanks for taking the time to make an issue!

I think you're right that the use of mediaQueries is unnecessary. If you wanted to make the change in a PR I would be happy to merge it. Otherwise I could do it later tonight.

**Comment by montemishkin** [comment]
Ahh yes, good catch!  And thanks for making the issue!

I think the fix we are after is very close to what you have, but more along the lines of

```js
// there is a window, so compute the true media type
return transform(mediaQueries, (result, query, type) => {
    // if the browser matches the media query
    if (matchMedia(query).matches) {
        // use the current media type
        return type
    }
    // otherwise the browser does not match the query 
    // so return the previous result
    return result
// start off the accumulator with the default value
}, defaultMediaType)
```

**Comment by aaivazis** [comment]
Hey @tstavinoha, the reason we want to use mediaquery is because it will match against different media types like portrait or landscape.

Regardless, I think you have found a bug in the reducer that we are investigating now.

**Comment by tstavinoha** [comment]
I'm not sure I'll catch the time to do a PR, especially because i cant write tests :)

However, what i would do is the following regarding dropping the media queries:

1. In the reducer factory, ditch the media queries and create an internal array of breakpoint data, sorted by width, e.g. `var sortedBreakpoints = Object.keys(breakpoints).map(bp => {return {value: breakpoints[bp], mediaType: bp}}).sort((a,b) => {return a-b})`
2. pass the width and sorted breakpoints to:
        
        function getMediaType(width = Infinity, sortedBreakpoints = []) {
            for (var i = 0; i < sortedBreakpoints.length; i++) {
            if (width < sortedBreakpoints[i].value) {
                return sortedBreakpoints[i].mediaType;
            }
        }

        return 'infinity';
}


let sortedBreakpoints = Object.keys(breakpoints).map(bp => {return {value: breakpoints[bp], mediaType: bp}}).sort((a,b) => {return a-b});

**Comment by montemishkin** [comment]
And yes, as @aaivazis notes, the use of the [mediaquery](https://github.com/axyz/mediaquery) library allows users to specify custom (non-numerical) media queries (such as `@media all and (color-index)`).  This [article](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) on MDN explains some of the other more exotic uses of media queries that do not quite fit into the more simple use case only involving screen widths.

**Comment by tstavinoha** [comment]
Alright, you guys know better than me what needs to be done with this lib :)

Glad i could point out a bug

**Comment by montemishkin** [comment]
No don't doubt yourself! :smiley: 

You bring up a great point and we are only discussing the relative merits of including / excluding the use of mediaquery.

Thanks for the tips, and feel free to (or not) continue to be a part of the discussion!

**Comment by aaivazis** [comment]
@tstavinoha I just pushed a fixed for your bug. Please let me know if you run into any more problems

**Comment by montemishkin** [comment]
For further discussion regarding the current implementation's design choice to

* allow for non-numerical breakpoints in the the `mediaType` property
* return false for any non-numerical breakpoint in the `greaterThan` and `lessThan` properties

see #4.
