### ISSUE TITLE
lessThan is actually lessThanOrEqualTo

### ISSUE THREAD

**Issue by tstavinoha** [aaivazis/redux-responsive#5]
Hey again :)

Here's a little cut-out:
![lessthan](https://cloud.githubusercontent.com/assets/10105376/10868839/87ee28cc-809b-11e5-900a-09178cd48417.jpg)
that shows that less than (lt, <) behaves like 'less than or equal' (lte, <=).

I don't think that the reducer should calculate all variants (`[ <, <=, =, >, >= ]`) because it does not hurt expressiveness too much - (`[<=, >, =]`) are just enough. Supporting too many operators would clutter the reducer and would require a different approach to breakpoint handling (calculations using both lower and upper media width range boundaries, instead of only the upper boundary).

However in the current state, lessThan is a little liar :)
I think that renaming it to something like lessOrEqual would benefit self-documentation and code legibility.

What do you guys think?

**Comment by aaivazis** [comment]
Hey @tstavinoha! Thanks for pointing this out. 

I think the right approach is to make lessThan work as labeled and not include the boundary. This means the reducer would only support `<, =, >`. How does that sound?
