### ISSUE TITLE
Can't run from src directory

### ISSUE THREAD

**Issue by CalebEverett** [aaivazis/redux-responsive#6]
Hi, thanks for this. I was trying to change your code to only update the store if the matchmedia changed, not with every window resizing. It looked like the package had a main specified of the build directory. I tried to change the package.json file to refer to the src directory to pick up the few changes I made, but got this error:
```
ERROR in ./~/redux-responsive/src/index.js
Module parse failed: D:\projects\rrum\node_modules\redux-responsive\src\index.js Line 2: Unexpected token
You may need an appropriate loader to handle this file type.
| // local imports
| import createResponsiveStateReducer from 'util/createResponsiveStateReducer'
| import addResponsiveHandlers from 'util/addResponsiveHandlers'
|
 @ ./src/redux/create.js 18:23-50
```

How can I set the the package up to be able to include the changed src files in my build process?

Thanks again,

**Comment by aaivazis** [comment]
Hey Caleb,

Thanks for contributing. It seems like webpack is saying that it doesn't know how to compile the es6 syntax in this file. My guess is that your webpack configuration excludes the node_modules directory. The quickest way to have your changes take effect would be to change the `main` attribute of the `package.json` to point back to `build/index.js` and run the following command at the root of your project:

`npm install ./node_modules/redux-responsive`

That will cause npm to rebuild `redux-responsive` with your changes (using the configuration included by this repo).

Let me know if that command doesn't work for you. I can't test it as I don't have a Windows machine (but it works on my mac).

**Comment by aaivazis** [comment]
You bring up a good point about only updating the store if the mediaType changed. If you're interested in sharing it I'd love to see what you come up with!

**Comment by montemishkin** [comment]
:+1: on seeing Caleb's changes!

(if he wants)

**Comment by CalebEverett** [comment]
awesome thanks, still hacking my way up the learning curve, but I'll give a go and share if it works

**Comment by aaivazis** [comment]
Awesome! I'll close this issue then. Feel free to reopen if you run into any more problems.

**Comment by CalebEverett** [comment]
ok, got through some windows errors, but now have this:

```
 redux-responsive@0.1.3 prepublish D:\projects\rrum\node_modules\redux-responsive                                  
 gulp build-production                                                                                             
                                                                                                                   
00:35:40] Requiring external module -babel-core/register                                                           
:\projects\rrum\node_modules\redux-responsive\node_modules\babel-core\lib\transformation\file\plugin-manager.js:164
     throw new TypeError(messages.get("pluginNotTransformer", name));                                              
     ^                                                                                                             
                                                                                                                   
ypeError: The plugin "typecheck" didn't export a Plugin instance

**Comment by aaivazis** [comment]
Hey Caleb, sorry it took me awhile to get back to you. I tried looking up your problem but couldn't find anything. Unfortunately, I'm not very familiar with Windows machines so I can't be much help :( 

But hopefully you can figure it out - I'd love to see what you're working on!

**Comment by CalebEverett** [comment]
Ok, thanks, it's probably something basic with javascript or config. If I come up with anything useful, I'll keep you posted.
